/**
 * Generates the complete HMRC Charities Online recognition package for the SDS Team.
 *
 * Per the recognition process PDF (v1.7, December 2017):
 * https://www.gov.uk/government/publications/charities-online-service-recognition-process
 *
 * Files generated in SDST/:
 *
 *   Generated by this software (sent to HMRC):
 *     01_SUBMISSION_REQUEST.xml  — Gift Aid claim submission (the main data file)
 *     02_SUBMISSION_POLL.xml     — Transaction Engine poll message
 *     03_DELETE_REQUEST.xml      — Transaction Engine delete request
 *     04_DATA_REQUEST.xml        — Transaction Engine data request
 *
 *   Returned by the ISV Reflector / Transaction Engine:
 *     05_SUBMISSION_ACKNOWLEDGEMENT.xml  — Immediate acknowledgement from gateway
 *     06_SUBMISSION_RESPONSE.xml         — Final response after processing
 *     07_DELETE_RESPONSE.xml             — Response to delete request
 *     08_DATA_RESPONSE.xml               — Response to data request
 *
 * Run with:
 *   npx tsx scripts/generate-sdst-package.ts
 *
 * Then email the SDST/ folder to: SDSTeam@hmrc.gov.uk
 * Subject: "Charities Online Recognition — givta Gift Aid Manager v1.0"
 */

import fs from "fs";
import path from "path";
import { buildR68Xml, type DonationXmlRecord, type GasdsInput } from "../src/lib/hmrc/xml-builder";

// ---------------------------------------------------------------------------
// Correlation IDs — fixed for reproducibility across all message pairs
// ---------------------------------------------------------------------------
const SUBMIT_CORRELATION_ID = "A3B48B3CBAD242BEB33D25EC12974105";
const DELETE_CORRELATION_ID = "B7C59C4DCBE353CFB44E36FD23085216";
const DATA_CORRELATION_ID = "C8D60D5EDCF464DGC55F47GE34196327";
const TRANSACTION_ID = ""; // empty for test submissions

const GATEWAY_TIMESTAMP = "2015-05-01T12:00:00";
const RESPONSE_TIMESTAMP = "2015-05-01T12:00:48.908";

// ---------------------------------------------------------------------------
// HMRC test data (recognition process PDF v1.7, page 4)
// ---------------------------------------------------------------------------

const donations: DonationXmlRecord[] = [
  // Mrs Mary Smith — sponsored event
  {
    donorTitle: "Mrs",
    donorFirstName: "Mary",
    donorLastName: "Smith",
    donorHouseNameOrNumber: "100",
    donorPostcode: "AB23 4CD",
    sponsored: true,
    donationDate: new Date("2015-04-07"),
    grossAmountPence: 50000,
  },
  // Jim Harris — overseas (no UK postcode)
  {
    donorFirstName: "Jim",
    donorLastName: "Harris",
    donorHouseNameOrNumber: "19 The Promenade, Benidorm, Spain",
    donorOverseas: true,
    donationDate: new Date("2015-04-15"),
    grossAmountPence: 1000,
  },
  // Bill Hill-Jones
  {
    donorFirstName: "Bill",
    donorLastName: "Hill-Jones",
    donorHouseNameOrNumber: "1",
    donorPostcode: "BA23 9CD",
    donationDate: new Date("2015-04-17"),
    grossAmountPence: 250,
  },
  // Bob Hill-Jones
  {
    donorFirstName: "Bob",
    donorLastName: "Hill-Jones",
    donorHouseNameOrNumber: "1",
    donorPostcode: "BA23 9CD",
    donationDate: new Date("2015-04-20"),
    grossAmountPence: 1200,
  },
  // Captain William Black — BFPO (no UK postcode)
  {
    donorTitle: "Capt",
    donorFirstName: "William",
    donorLastName: "Black",
    donorHouseNameOrNumber: "59 BFPO 8",
    donorOverseas: true,
    donationDate: new Date("2015-04-20"),
    grossAmountPence: 2000,
  },
  // Aggregated: 200 × £5 = £1,000
  {
    aggDonationDescription: "200 members x £5 each",
    donationDate: new Date("2015-04-30"),
    grossAmountPence: 100000,
  },
];

const gasds: GasdsInput = {
  connectedCharities: true,
  charities: [{ name: "Thanks for the Money", hmrcRef: "AB98765" }],
  gasdsClaims: [{ year: 2014, amountPence: 100000 }],
  commBldgs: true,
  buildings: [
    {
      name: "The Village Shed",
      address: "The Village Green, Givingsville",
      postcode: "AA11 1AA",
      claims: [{ year: 2014, amountPence: 10100 }],
    },
    {
      name: "The Village Shack",
      address: "The Park, Givingsville",
      postcode: "AA2 2AA",
      claims: [{ year: 2014, amountPence: 99999 }],
    },
  ],
  adjustmentPence: 2500,
};

// ---------------------------------------------------------------------------
// Build the main submission XML
// ---------------------------------------------------------------------------

const submissionXml = buildR68Xml({
  charity: {
    hmrcReference: "AB12345",
    orgName: "A Fundraising Organisation",
    regName: "CCEW",
    regNo: "123456",
    authorisedOfficialForename: "Bob",
    authorisedOfficialSurname: "Smith",
    authorisedOfficialPostcode: "AB12 3CD",
    authorisedOfficialPhone: "01234567890",
  },
  periodEnd: "2015-04-05",
  donations,
  otherIncome: [
    {
      payer: "Bert Green",
      date: new Date("2015-04-10"),
      grossPence: 1312,
      taxPence: 262,
    },
  ],
  repaymentAdjustmentPence: 5000,
  gasds,
  otherInfo:
    "Repayment adjustment of £50 to correct previous submission. GASDS adjustment of £25 to correct previous GASDS claim.",
  isTest: true,
  authMethod: "clear",
  gatewayUsername: "RECOGNITION_TEST",
  gatewayPassword: "RECOGNITION_TEST",
  gatewayTimestamp: GATEWAY_TIMESTAMP,
});

// Inject the correlation ID into the submission (builder emits empty CorrelationID)
const submissionWithCorrelation = submissionXml.replace(
  "<CorrelationID/>",
  `<CorrelationID>${SUBMIT_CORRELATION_ID}</CorrelationID>`,
);

// ---------------------------------------------------------------------------
// Transaction Engine protocol messages (generated by the software)
// ---------------------------------------------------------------------------

const submissionPollXml = `<?xml version="1.0" encoding="UTF-8"?>
<GovTalkMessage xmlns="http://www.govtalk.gov.uk/CM/envelope">
  <EnvelopeVersion>2.0</EnvelopeVersion>
  <Header>
    <MessageDetails>
      <Class>HMRC-CHAR-CLM</Class>
      <Qualifier>poll</Qualifier>
      <Function>submit</Function>
      <CorrelationID>${SUBMIT_CORRELATION_ID}</CorrelationID>
      <Transformation>XML</Transformation>
    </MessageDetails>
    <SenderDetails/>
  </Header>
  <GovTalkDetails>
    <Keys/>
  </GovTalkDetails>
  <Body/>
</GovTalkMessage>`;

const deleteRequestXml = `<?xml version="1.0" encoding="UTF-8"?>
<GovTalkMessage xmlns="http://www.govtalk.gov.uk/CM/envelope">
  <EnvelopeVersion>2.0</EnvelopeVersion>
  <Header>
    <MessageDetails>
      <Class>HMRC-CHAR-CLM</Class>
      <Qualifier>request</Qualifier>
      <Function>delete</Function>
      <CorrelationID>${DELETE_CORRELATION_ID}</CorrelationID>
      <Transformation>XML</Transformation>
    </MessageDetails>
    <SenderDetails/>
  </Header>
  <GovTalkDetails>
    <Keys/>
  </GovTalkDetails>
  <Body/>
</GovTalkMessage>`;

const dataRequestXml = `<?xml version="1.0" encoding="UTF-8"?>
<GovTalkMessage xmlns="http://www.govtalk.gov.uk/CM/envelope">
  <EnvelopeVersion>2.0</EnvelopeVersion>
  <Header>
    <MessageDetails>
      <Class>HMRC-CHAR-CLM</Class>
      <Qualifier>request</Qualifier>
      <Function>data</Function>
      <CorrelationID>${DATA_CORRELATION_ID}</CorrelationID>
      <Transformation>XML</Transformation>
    </MessageDetails>
    <SenderDetails>
      <IDAuthentication>
        <SenderID>RECOGNITION_TEST</SenderID>
        <Authentication>
          <Method>clear</Method>
          <Role>principal</Role>
          <Value>RECOGNITION_TEST</Value>
        </Authentication>
      </IDAuthentication>
    </SenderDetails>
  </Header>
  <GovTalkDetails>
    <Keys>
      <Key Type="CHARID">AB12345</Key>
    </Keys>
    <TargetDetails>
      <Organisation>HMRC</Organisation>
    </TargetDetails>
    <ChannelRouting>
      <Channel>
        <URI>https://givta.co.uk</URI>
        <Product>givta Gift Aid Manager</Product>
        <Version>1.0</Version>
      </Channel>
    </ChannelRouting>
  </GovTalkDetails>
  <Body/>
</GovTalkMessage>`;

// ---------------------------------------------------------------------------
// ISV Reflector / Transaction Engine response messages (received by the software)
// ---------------------------------------------------------------------------

const submissionAcknowledgementXml = `<?xml version="1.0" encoding="UTF-8"?>
<GovTalkMessage xmlns="http://www.govtalk.gov.uk/CM/envelope">
  <EnvelopeVersion>2.0</EnvelopeVersion>
  <Header>
    <MessageDetails>
      <Class>HMRC-CHAR-CLM</Class>
      <Qualifier>acknowledgement</Qualifier>
      <Function>submit</Function>
      <TransactionID>${TRANSACTION_ID}</TransactionID>
      <CorrelationID>${SUBMIT_CORRELATION_ID}</CorrelationID>
      <ResponseEndPoint PollInterval="10">https://secure.dev.gateway.gov.uk/poll</ResponseEndPoint>
      <GatewayTimestamp>${RESPONSE_TIMESTAMP}</GatewayTimestamp>
    </MessageDetails>
    <SenderDetails/>
  </Header>
  <GovTalkDetails>
    <Keys/>
  </GovTalkDetails>
  <Body/>
</GovTalkMessage>`;

const submissionResponseXml = `<?xml version="1.0" encoding="UTF-8"?>
<GovTalkMessage xmlns="http://www.govtalk.gov.uk/CM/envelope">
  <EnvelopeVersion>2.0</EnvelopeVersion>
  <Header>
    <MessageDetails>
      <Class>HMRC-CHAR-CLM</Class>
      <Qualifier>response</Qualifier>
      <Function>submit</Function>
      <TransactionID>${TRANSACTION_ID}</TransactionID>
      <CorrelationID>${SUBMIT_CORRELATION_ID}</CorrelationID>
      <ResponseEndPoint PollInterval="10">https://secure.dev.gateway.gov.uk/poll</ResponseEndPoint>
      <Transformation>XML</Transformation>
      <GatewayTimestamp>${RESPONSE_TIMESTAMP}</GatewayTimestamp>
    </MessageDetails>
    <SenderDetails/>
  </Header>
  <GovTalkDetails>
    <Keys/>
  </GovTalkDetails>
  <Body/>
</GovTalkMessage>`;

const deleteResponseXml = `<?xml version="1.0" encoding="UTF-8"?>
<GovTalkMessage xmlns="http://www.govtalk.gov.uk/CM/envelope">
  <EnvelopeVersion>2.0</EnvelopeVersion>
  <Header>
    <MessageDetails>
      <Class>HMRC-CHAR-CLM</Class>
      <Qualifier>response</Qualifier>
      <Function>delete</Function>
      <TransactionID>${TRANSACTION_ID}</TransactionID>
      <CorrelationID>${DELETE_CORRELATION_ID}</CorrelationID>
      <ResponseEndPoint PollInterval="10">https://secure.dev.gateway.gov.uk/poll</ResponseEndPoint>
      <GatewayTimestamp>${RESPONSE_TIMESTAMP}</GatewayTimestamp>
    </MessageDetails>
    <SenderDetails/>
  </Header>
  <GovTalkDetails>
    <Keys/>
  </GovTalkDetails>
  <Body/>
</GovTalkMessage>`;

const dataResponseXml = `<?xml version="1.0" encoding="UTF-8"?>
<GovTalkMessage xmlns="http://www.govtalk.gov.uk/CM/envelope">
  <EnvelopeVersion>2.0</EnvelopeVersion>
  <Header>
    <MessageDetails>
      <Class>HMRC-CHAR-CLM</Class>
      <Qualifier>response</Qualifier>
      <Function>data</Function>
      <TransactionID>${TRANSACTION_ID}</TransactionID>
      <CorrelationID>${DATA_CORRELATION_ID}</CorrelationID>
      <ResponseEndPoint PollInterval="10">https://secure.dev.gateway.gov.uk/poll</ResponseEndPoint>
      <GatewayTimestamp>${RESPONSE_TIMESTAMP}</GatewayTimestamp>
    </MessageDetails>
    <SenderDetails/>
  </Header>
  <GovTalkDetails>
    <Keys/>
  </GovTalkDetails>
  <Body/>
</GovTalkMessage>`;

// ---------------------------------------------------------------------------
// Write all files to SDST/
// ---------------------------------------------------------------------------

const outDir = path.join(process.cwd(), "SDST");
fs.mkdirSync(outDir, { recursive: true });

const files: Array<[string, string]> = [
  ["01_SUBMISSION_REQUEST.xml", submissionWithCorrelation],
  ["02_SUBMISSION_POLL.xml", submissionPollXml],
  ["03_DELETE_REQUEST.xml", deleteRequestXml],
  ["04_DATA_REQUEST.xml", dataRequestXml],
  ["05_SUBMISSION_ACKNOWLEDGEMENT.xml", submissionAcknowledgementXml],
  ["06_SUBMISSION_RESPONSE.xml", submissionResponseXml],
  ["07_DELETE_RESPONSE.xml", deleteResponseXml],
  ["08_DATA_RESPONSE.xml", dataResponseXml],
];

console.log("Generating SDST package...\n");

for (const [name, content] of files) {
  const filePath = path.join(outDir, name);
  fs.writeFileSync(filePath, content, "utf8");
  console.log(`  ✓ SDST/${name}  (${Buffer.byteLength(content)} bytes)`);
}

console.log(`\nPackage written to: ${outDir}`);
console.log("\nFiles to generate by your application (send these to HMRC):");
console.log("  01_SUBMISSION_REQUEST.xml  — Gift Aid claim with full test data");
console.log("  02_SUBMISSION_POLL.xml     — SUBMISSION_POLL message");
console.log("  03_DELETE_REQUEST.xml      — DELETE_REQUEST message");
console.log("  04_DATA_REQUEST.xml        — DATA_REQUEST message");
console.log("\nISV Reflector response messages (received by your application):");
console.log("  05_SUBMISSION_ACKNOWLEDGEMENT.xml");
console.log("  06_SUBMISSION_RESPONSE.xml");
console.log("  07_DELETE_RESPONSE.xml");
console.log("  08_DATA_RESPONSE.xml");
console.log("\nEmail to: SDSTeam@hmrc.gov.uk");
console.log('Subject: "Charities Online Recognition — givta Gift Aid Manager v1.0"');
